### ISSUE TITLE
Docker documentation

### ISSUE THREAD

**Issue by florian-ried** [jantari/rewinged#2]
Could you please provide a guide how to get it running on Docker?

**Comment by jantari** [comment]
Currently you can download the source code from one of the releases: https://github.com/jantari/rewinged/releases or directly with git, extract it if needed and run `docker build .` inside the directory. That will build a container according to the [Dockerfile](https://github.com/jantari/rewinged/blob/main/Dockerfile) that's included in the repository.

Then when you run the container you most likely want to mount some volumes for the package directory as well as certificate files for HTTPS.

I could look into publishing pre-built container images, that would make updating much easier as well, but currently you'll have to build the container yourself.

**Comment by fabiang** [comment]
I have created a public [Alpine image](https://hub.docker.com/r/fabiang/rewinged), which should help you getting Rewinged hosted. Source is here:  https://github.com/fabiang/docker-rewinged

It's completely untested, but has some feature missing from the Dockerfile provided with this project:
1. Run as separate user
2. Rewinged is compiled in "release mode"
3. Manifest path is created, so you can mount it as volume/bind

**Comment by jantari** [comment]
@florian-ried did this help you get running with docker?

**Comment by jantari** [comment]
I have decided to publish a prebuilt container image.

Version `0.3.1-rc.2` is the first, but a container image will be released for all new versions going forward. All containers will have a tag with their exact version, there is a `latest` tag that is always the very latest release (including prereleases like beta and rc!) and then there is a `stable` tag for any release that's not a beta or rc etc. prerelease. Since `0.3.1-rc.2` is currently the only image available, there is no `stable` yet.

There are no functional changes in `0.3.1-rc.2` compared to `0.3.0`, only the container-build was added, so if you're running the binary releases you don't have to update.

But, you can now get started with rewinged and docker just like this:

```
docker run ghcr.io/jantari/rewinged:0.3.1-rc.2
```

If anyone has feedback regarding the container image please feel free to open new issues about it, as it is now an official release artifact we can have issues and PRs on it.
